### ISSUE TITLE
クラスの分け方について

### ISSUE THREAD

**Issue by elliptic-shiho** [S--Minecraft/twgitter#1]
もし方針等が既に固まっているのであればスルーして下さい。

現在、すべてのIMインフラが個別にMessagesやConnection等を実装していますが、オブジェクト指向を意識してインターフェース/抽象クラスを利用してそれぞれのIMインフラクラスの対メインアプリケーション部分をすべて統一してみてはどうでしょうか。
現在の方式ですとそれぞれのIMインフラの初期化をすべて個別に書き、同じようなやりとりをすべて同一視できないクラスで書いているため、非常にコーディングがやりづらい印象です。

**Comment by S--Minecraft** [comment]
それは自分も思ってたんですが、とりあえず自分は経験浅いので動くものを書いてみたという感じですね。
（あまり継承・インターフェース等理解ができていないので…）
ここからtwgitter.generalなどに作っていけたらなとは思います。

どういうものが読みやすいコード・読みづらいコードかもわからないので…
このような意見はありがたいです。

**Comment by S--Minecraft** [comment]
Twgitter2に移行のためクローズ
